os: osx
osx_image: xcode12
language: cpp

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update > /dev/null ;
    brew tap Skycoder42/qt-modules
    brew install qt5 cmake boost catch2;
    brew link --force qt ;
    fi
  - export core_count=$(nproc || echo 4) && echo core_count = $core_count

before_script:
  - export PATH=/usr/local/opt/qt5/bin:$PATH
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - cmake --build . --target RadioTerm -- -j$core_count
  - #cmake --build . --target functions_test -- -j$core_count
  - #ctest functions_test
  - macdeployqt RadioTerm.app -always-overwrite -appstore-compliant
  - zip -r RadioTerm.zip RadioTerm.app

deploy:
  provider: releases
  file: "RadioTerm.zip"
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true

notifications:
  email:
    recipients:
      - minorsecond@gmail.com
    on_success: change
    on_failure: always